# Generated by Django 2.2 on 2020-09-20 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BillManagement', '0001_initial'),
        ('CustomerManagement', '0002_customer_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='bill',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='BillManagement.Bill'),
        ),
    ]
