# Generated by Django 2.2 on 2020-09-20 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerManagement', '0003_customer_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BillManagement.Bill'),
        ),
    ]
