# Generated by Django 2.2 on 2020-09-20 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BillManagement', '0001_initial'),
        ('CustomerManagement', '0005_remove_customer_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='bill',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='BillManagement.Bill'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Phone_Number',
            field=models.IntegerField(unique=True),
        ),
    ]
