# Generated by Django 2.2 on 2020-09-20 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerManagement', '0006_auto_20200920_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BillManagement.Bill'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='OrderManagement.Order'),
        ),
    ]
