# Generated by Django 2.2 on 2020-09-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_Type', models.CharField(max_length=100)),
                ('Order_Status', models.CharField(max_length=200)),
            ],
        ),
    ]
