# Generated by Django 2.2 on 2020-09-20 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OrderManagement', '0002_order_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BillManagement.Bill'),
        ),
    ]
