# Generated by Django 2.2 on 2020-09-20 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrderManagement', '0004_auto_20200920_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='bill',
        ),
    ]
