# Generated by Django 2.2 on 2020-09-20 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodManagement', '0005_food_merchant'),
        ('CustomerManagement', '0008_auto_20200920_1844'),
        ('MerchantManagement', '0006_auto_20200920_1844'),
        ('OrderManagement', '0005_remove_order_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CustomerManagement.Customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='food',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FoodManagement.Food'),
        ),
        migrations.AddField(
            model_name='order',
            name='merchant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MerchantManagement.Merchant'),
        ),
    ]
