# Generated by Django 2.2 on 2020-10-02 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderManagement', '0006_auto_20200920_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Order_Status',
            field=models.CharField(choices=[('Available', 'Available'), ('Pending', 'Pending'), ('Delivered', 'Delivered')], default='Available', max_length=50),
        ),
    ]
