# Generated by Django 2.2 on 2020-10-05 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrderManagement', '0009_order_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product',
            new_name='food',
        ),
    ]
