# Generated by Django 2.2 on 2020-10-07 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrderManagement', '0010_auto_20201005_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
    ]
