# Generated by Django 2.2 on 2020-10-07 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrderManagement', '0011_auto_20201007_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='merchant',
        ),
    ]
