# Generated by Django 2.2 on 2020-10-07 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrderManagement', '0012_auto_20201007_1354'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
