# Generated by Django 2.2 on 2020-09-20 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodManagement', '0002_food_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='OrderManagement.Order'),
        ),
    ]
