# Generated by Django 2.2 on 2020-09-20 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodManagement', '0003_auto_20200920_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='order',
        ),
    ]
