# Generated by Django 2.2 on 2020-09-20 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MerchantManagement', '0006_auto_20200920_1844'),
        ('FoodManagement', '0004_remove_food_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='merchant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MerchantManagement.Merchant'),
        ),
    ]
