# Generated by Django 2.2 on 2020-10-05 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodManagement', '0010_auto_20201004_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='Food_Image',
            field=models.ImageField(blank=True, default='images/default.jpg', upload_to='Foods/images/'),
        ),
    ]
