# Generated by Django 2.2 on 2020-10-05 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodManagement', '0011_auto_20201005_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='reviews',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
