# Generated by Django 2.2 on 2020-10-05 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodManagement', '0012_auto_20201006_0218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='Food_Desc',
        ),
    ]
