# Generated by Django 2.2 on 2020-10-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodManagement', '0015_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='reviews',
            field=models.ManyToManyField(to='FoodManagement.Review'),
        ),
    ]
