# Generated by Django 2.2 on 2020-09-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Payment_Type', models.CharField(max_length=100)),
                ('Total_Price', models.FloatField(max_length=200)),
            ],
        ),
    ]
