# Generated by Django 2.2 on 2020-09-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Merchant_Name', models.CharField(max_length=100)),
                ('Food_Name', models.CharField(max_length=200)),
                ('Business_Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=200, unique=True)),
                ('NID', models.CharField(max_length=200, unique=True)),
                ('Phone_Number', models.IntegerField(max_length=200, unique=True)),
                ('Address', models.CharField(max_length=200)),
            ],
        ),
    ]
