# Generated by Django 2.2 on 2020-09-20 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MerchantManagement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchant',
            old_name='Food_Name',
            new_name='M_Food_Name',
        ),
    ]
