# Generated by Django 2.2 on 2020-09-20 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MerchantManagement', '0005_auto_20200920_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='food',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='order',
        ),
    ]
