# Generated by Django 2.2 on 2020-09-24 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MerchantManagement', '0006_auto_20200920_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='constitution',
            field=models.FileField(default='exit', upload_to='files/constitution/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='merchant',
            name='logo',
            field=models.ImageField(default='exit', upload_to='images/logo/'),
            preserve_default=False,
        ),
    ]
