# Generated by Django 2.2 on 2020-09-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MerchantManagement', '0007_auto_20200925_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='logo',
            field=models.ImageField(default=1, upload_to='images/logo/'),
        ),
    ]
