# Generated by Django 2.2 on 2020-10-01 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MerchantManagement', '0008_auto_20200925_0130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='constitution',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='logo',
        ),
        migrations.AddField(
            model_name='merchant',
            name='Profile_pic',
            field=models.ImageField(default='default.jpg', upload_to='images/Profile_pic/'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
