# Generated by Django 2.2 on 2020-10-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MerchantManagement', '0009_auto_20201001_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='Email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='NID',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='Phone_Number',
            field=models.IntegerField(),
        ),
    ]
